### ISSUE TITLE
[Expanded Industry - 1.12.1] Casting Molds in all Creative Tabs

### ISSUE THREAD

**Issue by ghost** [Draco18s/ReasonableRealism#13]
All the casting molds from Expanded Industry appear in every creative tab.

**Comment by Draco18s** [comment]
This should be an easy fix.

**Comment by Draco18s** [comment]
Fixed and a build published.
I also added an Industry tab that has all the industry related items I could think of (hoppers, droppers, etc and most of Exp Ind's list of additions).
