### ISSUE TITLE
Regarding your build of COG (required for Ore Flowers, etc)

### ISSUE THREAD

**Issue by Dulciphi** [Draco18s/ReasonableRealism#17]
I've been trying to get CoFH ore gen working with Ore Flowers and was unable to make progress for about a week. I eventually gave up and started trying to use COG to generate ores. That's when I discovered that most of COG' default config files contain outdated mod IDs and block names. It's just dawned on me that this would be why I wasn't seeing any ore flowers in my CoFH generated copper veins (or Osmium veins, tin, aluminium and all the other mod ores). 

So far, I've gone through COG's configs and replaced the following mod IDs (I've just been saving the files as custom configs and loading them).

thermalfoundation
mekanism
magneticraft
immersiveengineering
forestry
biomesoplenty

I've also had to change block IDs within those configs. But that's just to get those blocks to generate in the world. I haven't seen any ore flowers for mod-added blocks yet ...and I'm not going to, am I? [edit - just to clarify, Ore Flowers is only indicating Vanilla ores and Harder Ores blocks. Ore Flowers don't appear for Thermal Foundation copper ore any other mod-added ore block].

I know the ore flowers work with Harder Ores. We considered using Harder Ores as well. The thing is, @CosmicDan has made a little mod for Rich Ore Variants. They drop normal ore blocks (meaning they can be processed by the machinery we have. That's why we're not just using harder ores. We need the ore blocks to drop as ore blocks)

The idea was to generate ores in a similar manner to HarderOres, with the most rich variants in the motherload. We want/need these deposits to be indicated by Ore Flowers. But it seems that I can't even get Ore Flowers to indicate for the basic Thermal Foundation Copper Ore. My understanding was that Ore Flowers match for ore dictionary entries. The copper ore is oredicted as "oreCopper". 

I also have B: processOreDictLatest=true

**Comment by cosmicdan** [comment]
EDIT: Disregard the email notification for my reply if you got it - I misread the issue. I'm actually not even clear on the problem, so don't mind me.

**Comment by Dulciphi** [comment]
To be clear, 
Ore Flowers don't work unless I'm specifically using Harder Ores blocks in COG config.
No other mod ore blocks (generated by COG or CoFH) are producing Ore Flowers at all. 

I haven't yet generated any Rich Ores. I wanted to get the ore generation and ore flowers working, then add the rich ore variants to the working configs.

**Comment by Draco18s** [comment]
This really should be reported to [COG over here](https://github.com/lawremi/CustomOreGen/issues). That said, I probably have some instances of these identifiers within my own configs, so I'm glad you brought it up.

**Comment by Dulciphi** [comment]
I've reported the ModID and BlockID issue to COG, but what about the Ore Flowers only indicating for Vanilla ores (gold, iron, diamond, redstone) and Harder Ores blocks, but not for other mod-added ores like Thermal Foundation copper, etc? Is that a related issue?

**Comment by Draco18s** [comment]
I duo have to handle some of it myself.

**Comment by Draco18s** [comment]
Finally got around to this. Looks like the only ID I actually use was ThermalFoundation (now replaced). Any block detection I do via oredict name. If you know of another something that needs to get fiddled with, feel free to reopen this.
