### ISSUE TITLE
Questions: What is salt used for?

### ISSUE THREAD

**Issue by Swelem** [Draco18s/ReasonableRealism#18]
Hey, I've been finding salt ore around rivers and oceans lately and wandered what it was used for
Harder farming on 1.12.2

**Comment by Draco18s** [comment]
It is used in the tanning rack to cure leather faster

**Comment by Swelem** [comment]
Thats great
Oh and by the way...My server crashes whenever someone comes near a polar bear(ticking entity)...idk if it was fixed in the last update tho

**Comment by Draco18s** [comment]
Should've been.

**Comment by Swelem** [comment]
Also there was a compatibility issue with the weather2 mod and tough as nails..Your mod only detects vanilla rain and doesn’t detect weather2 rain...so no hydrometer...And your thermometer doesn’t detect tough as nails seasons so there goes the thermometer...Should I make another issue over this

**Comment by Draco18s** [comment]
Yes, please do that. I likely won't be looking into it soon, but knowing it is a problem is good.
