### ISSUE TITLE
Animals don't die of old age

### ISSUE THREAD

**Issue by ghost** [Draco18s/ReasonableRealism#21]
Mod: Harder Farming
Minecraft Version: 1.12.2
Forge Build: 2555
Mod Version: 4.0.0d

While animals breed naturally just fine, they aren't dying off naturally, so the world fills with passive mobs over time.

**Comment by Draco18s** [comment]
Interesting. I can't take a look at this any time soon, but thanks for the report.
(My computer / dev box is unplugged and in the back of my car)

**Comment by Draco18s** [comment]
Dev box set up!
I have no idea what's going on and can't replicate.
Have you modified the configs at all?

**Comment by ghost** [comment]
My config is here; https://pastebin.com/FkwrtxUj

Also worth noting that animals will naturally breed even while swimming, and the water fills up with animals.

**Comment by Draco18s** [comment]
Nothing unusual there.
Any other mods installed? Does it still happen with only Harder Farming?

**Comment by ghost** [comment]
Okay, so I can't reproduce this with just Harder Farming either, therefore it's probably a mod interaction. I've got 120+ mods in my pack, and I'm not sure which ones are interacting with Harder Farming.

**Comment by Draco18s** [comment]
Yeah that makes things tricky. The best you can do is a binary elimination: remove half the mods (Harder Farming always staying in). If it goes away, add half of the removed ones back. If its still there, remove another half. Eventually (about 7 steps for 120 mods) you'll find the culprit.

**Comment by ghost** [comment]
Admittedly, I'm not willing to spend 3+ hours testing for it, so go ahead and close this if you like.

**Comment by Draco18s** [comment]
No worries. If you ever do figure it out, you can reopen the issue. In the meantime you can try disabling the aging mechanic entirely.
