### ISSUE TITLE
[1.12.2] HarderFarming nullpointerexceptions

### ISSUE THREAD

**Issue by Matryoshika** [Draco18s/ReasonableRealism#23]
Minecraft: 1.12.2
Harder Farming: 4.0.0d
Forge: 14.23.4.2739
OpenTerrainGenerator: v6

First I got a [nullpointer for ticking world](https://gist.github.com/Matryoshika/61b3b1e1acaa3662f1b0870198bb0582).
I then relaunched the pack without any coremods (well, bar OTG's) to make sure that they are not causing any mischief, which has led me to a second [nullpointer while updating neighbours](https://gist.github.com/Matryoshika/3d0fa7ca0e27ba84c56ed21d50dc1506).

I am seeing this happen in worlds with OpenTerrainGenerator, using _custom_ biomes, a feature of said mod.
This is happening no matter which value `B:EnableCropSlowingByBiome` is set to.

**Comment by Draco18s** [comment]
Interesting. Thanks for the report. 
The crash is helpful (narrows down the possible cause to [a single method](https://github.com/Draco18s/ReasonableRealism/blob/master/src/main/java/com/draco18s/farming/FarmingEventHandler.java#L484) but the line number is useless. :\

(Both crashes are the same, which is good)

I suspect something is going on with the biome there on 487 or 488, but I'm not sure why.

**Comment by Draco18s** [comment]
I'm forwarding this issue to OTG.
https://github.com/PG85/OpenTerrainGenerator/issues/196

**Comment by Draco18s** [comment]
Realized the line number isn't useless as I was looking at the wrong branch.
And the newly opened issue #27 gave me line 645. Which at least is in the right method...my dev copy is likely out of date and shifted something around.

And I think I figured out the problem.

**Comment by LemADEC** [comment]
Issue is reproduced without OTG.

**Comment by LemADEC** [comment]
This NPE is lagging our server. Any chance you push your latest changes so we can look into it?
In our case, it happens in Thaumcraft's Magical Forest. From a quick check in the code, the mod is caching biome temperatures. I suspect this is done too soon (i.e. before other mods have registered their biomes).

I'm a bit confused on why there's Map from Biomes to temperature since we can directly call getTemperature() on the biome. Is it to adjust those values from their default?

**Comment by Draco18s** [comment]
New version of the jar already went up with the issue fixed.

> I'm a bit confused on why there's Map from Biomes to temperature since we can directly call getTemperature() on the biome. Is it to adjust those values from their default?

Yes, it is/was to handle seasonal shifts, even if there are no current seasonal shifts. I wanted to rely on a separate mod (e.g. Stellar Sky) to handle year-time and just never got around to getting things worked out.

**Comment by LemADEC** [comment]
6.0.0a is reproducing the issue, so I guess the patch is partial?

**Comment by Draco18s** [comment]
I'll take another look, thanks.
(And push the code to git when I get a chance)

**Comment by Draco18s** [comment]
*Recheck*
Oh, the thing I thought I did that would (should?) have fixed it got lost. Pushing a new version of H.F. soon.
