### ISSUE TITLE
can't craft diamonds

### ISSUE THREAD

**Issue by jotac0** [Draco18s/ReasonableRealism#25]
so, i went mining for diamonds, but now i can't turn those raw diamonds in diamonds.
I did check the code, the packager should solve it, but it does not work, accepts the items but does nothing
(plus it made a tiny iron pile out of nowhere.
i am using:
1.12.1-HarderOres-4.0.0b
1.12.1-Harderfarming-4.0.0d
1.12.1-HardLib-v4
1.12.1-OreFlowers-4.0.0a
plus other mods
so ... is this the way to make diamonds?

**Comment by Draco18s** [comment]
That's really odd.
I'll take a look at this.

**Comment by Draco18s** [comment]
Huh. I apparently never added the recipe for diamonds. I'm surprised it took this long for anyone to notice...

**Comment by Draco18s** [comment]
If you shove this file into the jar inside assets/harderores/recipes/ore, that'll fix until I push a new build.
https://github.com/Draco18s/ReasonableRealism/blob/1.12.1/src/main/resources/assets/harderores/recipes/ore/diamond_chunk.json

**Comment by jotac0** [comment]
well .. i added a ender io recipy to fix it for now.
But thanks :)
