### ISSUE TITLE
Mobs still dropping leather

### ISSUE THREAD

**Issue by LemADEC** [Draco18s/ReasonableRealism#26]
As of 1.12.1-4.0.0d, some vanilla mobs are still dropping leather:
- Llama
- Horse
- Donkey
- Mule

**Comment by Draco18s** [comment]
I'll take a look at this.

**Comment by LemADEC** [comment]
As a bonus, if you could scan other mob drops and change leather to raw hide in them, that would be great <3

**Comment by Draco18s** [comment]
Fixed for the next release. Thanks for the report.
And I've made it so that any mob that would normally drop leather instead drops raw hide.
Should I also replace the rabbit skin -> leather recipe?

**Comment by LemADEC** [comment]
yes, the 4 rabbit hides into leather should be replaced too.
