### ISSUE TITLE
Silk touch on harder ores cause duplication.

### ISSUE THREAD

**Issue by The-Arcanian** [Draco18s/ReasonableRealism#30]
Using a Silk Touch pickaxe on a harder ore will drop a block with that meta value, but the block that was mined will also stay with one less meta value.

Minecraft 1.12.2
Forge 14.23.4.2739
HarderOres 6.0.0a

**Comment by Draco18s** [comment]
Clever. Thanks for the report. I'll look into this.

**Comment by Draco18s** [comment]
Was able to resolve this pretty easily. Thanks for the continued reports.

**Comment by The-Arcanian** [comment]
No problem. I was just trying to test out mod pack ideas. And breaking something every time. 😛

**Comment by Draco18s** [comment]
Oh sure. And I can't test everything! I just kind of assume that it'll either work with other mods, or it won't, and if it doesn't, someone will let me know and I can see what I can do about it.
