### ISSUE TITLE
Cannot craft Iron Powder more than once

### ISSUE THREAD

**Issue by Compsogbrickus** [Draco18s/ReasonableRealism#32]
After getting a source of Tiny Iron Powder, I attempted to craft Iron Powder. This worked the first time, and I was able to craft 20 at one time. When I re-entered the crafting table a second time, the recipe no longer functioned. Restarting the game fixes the issue until more Iron Powder is crafted.

Edit: It seems that when it does craft, the output is doubled for every click.

Latest 1.12.2 version of Harder Ores + dependencies.
![2018-09-09_18 54 02](https://user-images.githubusercontent.com/17102273/45269798-d305cc00-b461-11e8-850b-7099cac36746.png)

**Comment by Draco18s** [comment]
Looking into it. Thanks for the report.
Found the problem. Fixed in dev, will push a build soon as the workaround requires completely shutting down the game and restarting.
