### ISSUE TITLE
problem with the sluice

### ISSUE THREAD

**Issue by jotac0** [Draco18s/ReasonableRealism#35]
when you place a sluice and start gathering those sweet ores, you will find that the ore value in the chunk will increase instead of decreasing, until it gets to exactly 0 :o

i expected the ore value to go down, not up

**Comment by Draco18s** [comment]
That's very interesting. I'll take a look when I get a chance.

**Comment by Draco18s** [comment]
Yep, the value being sent by the sluice was wrong. Easy enough to confirm, thanks for the report!
