### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by viveleroi** [Draco18s/ReasonableRealism#41]
What license is this source under? I don't see one and was hoping to use, with attribution, a modified version of the LootUtil file.

**Comment by Draco18s** [comment]
Generally I consider my code to be under a "can view for reverence reasons" type license, but with my core library mod (basically, all of hardlib) as well as general things ("this is how I made my own machine with recipes") I don't have an issue with things being used (my line general falls along "you can use the source to learn how to do things or write plugins against my code, but don't walk off with my blocks and items wholesale"). The util libraries I've given to people before; they are particularly useful to folks and recreating that work is a headache and I don't mind sharing the work I did.

So on that, feel free to CBA. If you new functionality add to it, feel free to do a PR.

**Comment by viveleroi** [comment]
Thanks, the loot table stuff is definitely a headache hence why I'd like to get a head start with the loot util. I likely won't add functionality, but I don't need all of it either. I mainly want it to add custom loot for vanilla mobs (I could use the LivingDropsEvent but loot tables is recommended I hear)

I'm currently likely to use it here: https://github.com/viveleroi/DarkMythos

**Comment by Draco18s** [comment]
No reason to truncate it, never know when the other bits might come in handy.

Anyway, just make sure you use your own package name so conflicts don't happen. :)
