### ISSUE TITLE
HardLib causing massive world lag when crafting in servers

### ISSUE THREAD

**Issue by lgnmcrules** [Draco18s/ReasonableRealism#43]
I run a modded MC server, and this packs's HardLib causes thousands and thousands of lines of code to be run in the console of the server whenever anyone crafts anything in the crafting table.  This often results in players timing out and general annoyance whenever crafting literally anything.

Here's an example of what it does: 
```
"
31.07 22:51:01 [Server] Server thread/WARN [hardlib]: Fancy Seared Bricks Stairs
31.07 22:51:01 [Server] Server thread/WARN [hardlib]: false || false
31.07 22:51:01 [Server] Server thread/WARN [hardlib]: Seared Cobblestone Stairs
31.07 22:51:01 [Server] Server thread/WARN [hardlib]: false || false
31.07 22:51:01 [Server] Server thread/WARN [hardlib]: Seared Furnace Controller
31.07 22:51:01 [Server] Server thread/WARN [hardlib]: false || false
"
```
And it does this for thousands of lines.  It's like it has to look at every crafting recipe from every other mod every time the crafting table updates!  It's ridiculous!

**Comment by Draco18s** [comment]
See PR #40, which already took care of it (I just don't know how I missed seeing it). It also has updated jar files.

**Comment by lgnmcrules** [comment]
Do I just take out the 1.12.1-HardLib-v7.jar and replace it with the first link in that post?  If that's the case, it crashes my server

**Comment by Draco18s** [comment]
Veo compiled it and I noticed that he didn't update the version numbers. I vaguely recall the conversation (I was borderline without a computer at the time). You will probably need the other jars that you're using as well. I'm trying to set up a new workspace on my current machine to do a build for Curse, so if that doesn't work, I'll have that done...hopefully this evening.
