### ISSUE TITLE
[Harder Farming] Undead horses dying?

### ISSUE THREAD

**Issue by theavandiepen** [Draco18s/ReasonableRealism#47]
I know you haven't been doing anything with Minecraft mods for a while, so I know this may be a long shot, but:

Skeleton horses (and I'm guessing also zombie horses) die like other animals do with Harder Farming, but because they can't actually breed, they just all die off. They go into love mode, though, which is entertaining xD Either way, though, it doesn't make sense for an undead being to die of old age. Also I have four skeleton horses thanks to a skeleton trap and I don't want to keep cheating to replace them xD

Would you be able to make it so undead horses aren't affected by Harder Farming's animal mechanics? The config file doesn't have a way to make certain animals exempt from aging; there's just the global on/off for all animals.

**Comment by Draco18s** [comment]
Ah yes, super old code applying to mobs that don't spawn all that naturally to begin with.... hehe
There is a per-animal config, though because of how horses work I don't think it would work for *just* the undead ones. :\

In theory I could probably fix it, but it wouldn't be easy.

**Comment by theavandiepen** [comment]
Haha, yeah, I’ve been playing Minecraft since it was in beta and this was my first natural encounter with a skeleton trap. I was delighted

I could try the per-animal config and see what happens. Where is it/how would I do it? I’ve been trying but I can’t find it (my Minecraft version is 1.12.2)

Also I was looking at the source code for animal aging and if I’m correct (I’m not super code savvy), if an animal has an owner, it doesn’t age? 

Since skeleton trap horses are tame when they spawn (rather than a player taming them) I’m thinking they don’t have an owner attributed to them. If so, if I use a command to make me their owner, that would solve the problem (and would explain why my tame wolves aren’t dying, which I’m glad about!)

**Comment by Draco18s** [comment]
1.12 would actually be [this repo](https://github.com/Draco18s/HarderStuff/) but it's fine.

Oh well shit. Setting the accelerated age rate to `0` was the *intended* solution, but that'll actually cause a Divide By Zero error.

Darn.

**Comment by theavandiepen** [comment]
Oh whoops. This is where the source link in CurseForge took me

Whoops

Was I right about an animal with an owner not aging, though?

**Comment by Draco18s** [comment]
Yeah I updated the source link when the new version came out. It's fine though, same project, just things changed so drastically I didn't "port" so much as "rewrite from scratch."

> Was I right about an animal with an owner not aging, though?

[Yes](https://github.com/Draco18s/HarderStuff/blob/master/src/main/java/com/draco18s/wildlife/entity/ai/EntityAIAging.java#L55-L60).

**Comment by theavandiepen** [comment]
Gotcha!

Okay, perfect, I read that right. Now I can death proof them :D

**Comment by theavandiepen** [comment]
All right, it looks like donkeys, llamas, and mules are also being affected by this, and skeleton horses still die if they have an owner. (And I'm guessing zombie horses are similarly affected)

BUT I found the fix!

If you change EntityHorse to [AbstractHorse](https://maven.thiakil.com/forge-1.12-javadoc/net/minecraft/entity/passive/AbstractHorse.html) in two spots of the code section you linked me to, it'll make all of the above stop aging when they're tame, and horses will continue to work as intended. For skeleton horses, this would make them unaging from the get go since they spawn tame.

So basically, if I'm right about this, you want that section of code to read:

		if(entity instanceof AbstractHorse) {
			return !((AbstractHorse)entity).isTame();
		}
		else if(entity instanceof IEntityOwnable) {
			return ((IEntityOwnable)entity).getOwner() == null;
		}

And that would fix it!

Also, looking at the dates for releases [on Curseforge](https://www.curseforge.com/minecraft/mc-mods/harder-farming/files/2602246) and comparing them to the commits on this repo and the other you linked me to, it looks like the 1.12.1 branch in this repo is the source for the jar I've got in my mods folder, even with releases just for version parity taken into account.

**Comment by Draco18s** [comment]
Yeah, I was pretty sure you were on that version, as 1.14+ doesn't have this dumb logic. Mostly because it never really worked all that well even when there weren't issues like this.

I'm not sure I have a functional 1.12 workspace atm, but I'll check.

**Comment by theavandiepen** [comment]
Haha, we all learn how to do things better after we do them not so great.

Sounds good! If I could do the thing and save you some time, I definitely would

**Comment by Draco18s** [comment]
Good news, I have a functional 1.12 workspace.

But I don't have RR's ("Harder Stuff") source in it. I can pull the java code just fine, but I never pushed the resources, so lets see if I can recover those from somewhere...

**Comment by theavandiepen** [comment]
Huzzah! And fingers crossed!

**Comment by Draco18s** [comment]
Nah, the stuff exists. I just didn't want to have to pull apart a jar file for them.

Also need COG's source, located, fetching...

**Comment by Draco18s** [comment]
Oh.
This is.
Depressing.

I don't need a _1.12_ workspace. I need a _1.7.10_ workspace.

I forgot how old this sh!t is. XD

I now have to scour _even older_ hard drives to see if I can scrape together the required bits, because the Forge mdk urls changed and it's no longer possible to run setup (which has been true for like, ten years). **In theory** I can do this.

**Comment by theavandiepen** [comment]
Oh dear lord, this is certainly one heck of a search xD

**Comment by Draco18s** [comment]
Yeah, it is. All the files are in one place, in my old-old user directory. It's a matter of seeing if I can still open the workspace, as there may be other files that are required stored in other parts of the file system.

**Comment by Draco18s** [comment]
Almost there.
Almost there.
Project is open and there are no errors. Just need to figure out how to set up a run configuration...

**Comment by Draco18s** [comment]
Ok, can't run things in the workspace, but after some updated maven URLs I *can* compile. So that'll have to do.

**Comment by Draco18s** [comment]
Alright, give this a shot:
[Full mod set](https://www.dropbox.com/s/qmn6zl7udjkni6y/1.7.10-ReasonableRealism-15.26.1acaea.jar?dl=0) or [Just Wildlife](https://www.dropbox.com/s/nwe5w3gslaqyfrt/1.7.10-HarderWildlife-15.26.1e.jar?dl=0)
Depending on how you acquired things originally.

**Comment by theavandiepen** [comment]
Testing it right now- will let you know what happens!

**Comment by theavandiepen** [comment]
All right, so the mod isn't loading at all, but that would be because it's for the wrong Minecraft version, looks like.

[This is the version I originally got](https://www.curseforge.com/minecraft/mc-mods/harder-farming/files/2615230)

**Comment by Draco18s** [comment]
Ah! That is 1.12, I'll try again this evening. That source will be easier to set up.
Derpity derp derp.

**Comment by theavandiepen** [comment]
Hahaha no worries

**Comment by Draco18s** [comment]
Alright, lets try this again.

https://www.dropbox.com/s/dkc0pkm44iikgg9/1.12.1-Harderfarming-7.0.0b.jar?dl=0

**Comment by theavandiepen** [comment]
Huzzah!

I can confirm:

- the mod loaded
- untamed llamas, donkeys, and mules die, while the tame ones don't
- undead horses remain gloriously undead regardless
- if you set the global age rate at the highest possible and the maximum animal age at the lowest possible, some animals will start dying the moment they spawn, but this doesn't happen with default/less extreme settings (something I inadvertently found while testing xD )

**Comment by Draco18s** [comment]
All undead of all sorts are skipped now. Found a getCreatureType method that has an UNDEAD value.
As for extreme numbers: not gonna fix it. :p It was literally allowed to go that high precisely *because* someone wanted animals to die instantly and I went "shrug, don't see why not."

Its not really a rational value at that point; less of a bug and more of a developer tool.

**Comment by theavandiepen** [comment]
Oh, nice!

Haha, yeah it didn't seem like a bug tbh. I just thought it was entertaining and made sure it was just due to config settings and nothing else (for my own peace of mind, if nothing else)

Thank you so much for doing this! I really appreciate you taking the time to fix this issue
