### ISSUE TITLE
Use mod IDs. I have no clue what 'class names' are for animals.

### ISSUE THREAD

**Issue by MagmaSlime123** [Draco18s/ReasonableRealism#50]
![image](https://user-images.githubusercontent.com/51277766/173971414-b20e6d96-5e5f-480a-86e2-b3d9ee7eeeb1.png)

**Comment by Draco18s** [comment]
Man, I wrote that code...three years ago, no wait six. That's actually [this repo](https://github.com/Draco18s/HarderStuff).
Registry names *didn't exist* then.

Anyway, if you make a reasonable guess, the system [might be able to figure out what you actually want](https://github.com/Draco18s/HarderStuff/blob/master/src/main/java/com/draco18s/wildlife/util/AnimalUtil.java#L107-L114) and log it.

Also no, I'm not going to go fix my shitty 1.7 code, the entire animal aging system didn't work out very well.
