### ISSUE TITLE
Et Futurum Requiem compatibility

### ISSUE THREAD

**Issue by Redgi110** [Draco18s/ReasonableRealism#52]
I understand that Harder Underground for 1.7.10 has not been updated for a long time, but just want to say that Et Futurum Requiem using translation keys tile.etfuturum.granite/diorite/andesite instead tile.etfuturum.stone_granite/diorite/andesite

**Comment by Draco18s** [comment]
Noted, thank you. :)

Likely won't ever actually get around to fixing anything wrong with the 1.7.10 versions, much less updating Underground as-is to modern Minecraft.
