### ISSUE TITLE
Sifter doesn't collect dusts that fall on top of it

### ISSUE THREAD

**Issue by nornagon** [Draco18s/ReasonableRealism#6]
![Pile of Tiny Iron Dust resting on top of a sifter but not being collected](https://cloud.githubusercontent.com/assets/172800/21537107/2a04df32-cd41-11e6-88fb-5b71af0ce0d1.png)

It doesn't seem to matter whether the millstone drops the dust or if the player does. The only way I've been able to get it to work is to open the sifter UI and place the dust in the slot.

Other mods I'm running that might possibly be interfering via oredict or something: Immersive Engineering, Tinker's Construct, Railcraft.

PS, let me know if there's a better place to report issues!

**Comment by Draco18s** [comment]
Thanks for the head's up, I'll take a look at this in the morning.

**Comment by Draco18s** [comment]
Alright, fixed for next build.  There was some miscalculation in the AABB volume it was trying to find items in.

**Comment by nornagon** [comment]
Thanks for the super quick fixes! :D
