### ISSUE TITLE
[Harder Farming] Ticking entity crash

### ISSUE THREAD

**Issue by WesCook** [Draco18s/ReasonableRealism#7]
I've installed 1.10.2-HarderFarming-1.1.0a.jar into my in-development pack, and quickly came across an issue with ticking entities.

Crashlog: http://pastebin.com/AnKMPXtM

Once it triggered, loading that world at all would lead to the same crash.  Removing the mod was the only way to load that world again.

**Comment by Draco18s** [comment]
The crash is pure vanilla in nature.  Somehow EntityAIAttackMelee is being executed with a null attack target.  I am not sure how my code would cause that.

Try setting GlobalAgeRate to 0 in the config and see if that helps.

**Comment by WesCook** [comment]
Yep, that was it.  Setting GlobalAgeRate to 0 resolved the error.

I removed all but Harder Farming and Hardlib however and am not seeing the same crash, so it must be from a cross-mod issue.  I'll do some further testing to see if I can learn more.

**Comment by WesCook** [comment]
I've found the conflict.  It's the [Improving Minecraft](https://minecraft.curseforge.com/projects/improving-minecraft) mod, v1.12.1.

It adds wild variants of each farm animal (Wild Sheep, Wild Pig), and that seems to be creating the problem.  You can see in the crashlog it was a ticking EntityWildSheep.

**Comment by Draco18s** [comment]
Thanks for finding the conflict. Not sure what I'll be able to do about it, but I'll take a look in the morning.

Just FYI, the next build is going to inadvertantly revert all TileEntity data to fresh (tanning rack, millstone, sifter, etc) as another conflict was discovered and there's no way to fix it other than renaming my TE registration names, which means they can't be loaded from disk properly (and there's no fallback code other than to instance a new TE).  Just make sure you empty them of their contents (or break them so they aren't in the world at all) prior to updating.

**Comment by WesCook** [comment]
Thanks for the heads up, but that won't be a problem.  I'm still building my pack and was testing Harder Farming (and the other Reasonable Realism mods) once I noticed they'd been updated to 1.10.2.

I had actually wanted to include them in a 1.7 pack I'd built, but the dependency on COG was too heavy on my TPS.  So I'm glad to see that's not the case with all of the mods this time around.
