### ISSUE TITLE
Ore Flowers Pick Block Crash

### ISSUE THREAD

**Issue by bgoupille** [Draco18s/ReasonableRealism#8]
In creative mode, use the pick block button while looking at the stem block of a ore flowers tall flower.

Crash log:
[crash-2017-01-12_19.56.08-client.txt](https://github.com/Draco18s/ReasonableRealism/files/703274/crash-2017-01-12_19.56.08-client.txt)
Client log:
[client log.txt](https://github.com/Draco18s/ReasonableRealism/files/703276/client.log.txt)

**Comment by Draco18s** [comment]
I'll take a look at this soon.

**Comment by Draco18s** [comment]
Found and fixed the problem.
