### ISSUE TITLE
[Harder Ores - 1.10] Sugar from sifter has broken texture

### ISSUE THREAD

**Issue by ghost** [Draco18s/ReasonableRealism#9]
When putting 8 tiny sugar dust into the sifter the result is sugar, but the texture is broken. I assume this is because the[ output meta is 1](https://github.com/Draco18s/ReasonableRealism/blob/9e7d420ed7fc2805f3a79ac2b7f57e263107976c/src/main/java/com/draco18s/ores/OresBase.java#L527) when it should be 0

**Comment by Draco18s** [comment]
The git is out of date, actually. My dev code has it correct.
